[package]
name = "moon-provider-ollama"
description = "Proveedor Ollama para moon (API nativa)"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
moon-core    = { workspace = true }
async-stream = { workspace = true }
async-trait  = { workspace = true }
bytes        = { workspace = true }
chrono       = { workspace = true }
futures-util = { workspace = true }
reqwest      = { workspace = true }
serde        = { workspace = true }
serde_json   = { workspace = true }
tokio        = { workspace = true }
tokio-util   = { workspace = true }
tracing      = { workspace = true }

[dev-dependencies]
wiremock = { workspace = true }
