[package]
name = "moon-tui"
description = "Interfaz de terminal de moon"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = ["clipboard"]
clipboard = ["dep:arboard"]

[dependencies]
moon-core      = { workspace = true }
anyhow         = { workspace = true }
arboard        = { workspace = true, optional = true }
base64         = { workspace = true }
chrono         = { workspace = true }
crossterm      = { workspace = true }
futures-util   = { workspace = true }
nucleo-matcher = { workspace = true }
pulldown-cmark = { workspace = true }
ratatui        = { workspace = true }
syntect        = { workspace = true }
sysinfo        = { workspace = true }
tokio          = { workspace = true }
tokio-util     = { workspace = true }
tracing        = { workspace = true }
unicode-width  = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
